pub const TERRAIN_CHUNK_LENGTH: u32 = 1 << 8;
pub const TERRAIN_CHUNK_VOLUME: u32 = TERRAIN_CHUNK_LENGTH.pow(3);

pub const VOXELS_PER_WORLD_UNIT: u32 = 4;
pub const VOXEL_WORLD_UNIT_LENGTH: f32 = 1.0 / VOXELS_PER_WORLD_UNIT as f32;
