[package]
name = "rogue"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.6.0"
bytemuck = { version = "1.16.1", features = ["derive"] }
cfg-if = "1"
downcast = "0.11.0"
egui = { git = "https://github.com/emilk/egui.git" }
egui-winit = { git = "https://github.com/emilk/egui.git" }
epaint = { git = "https://github.com/emilk/egui.git", features = ["bytemuck"] }
env_logger = "0.11.3"
fixedbitset = "0.5.7"
nalgebra = "0.33.0"
hecs = "0.10.4"
include-wgsl-oil = "0.2.6"
log = "0.4.21"
parking_lot = "0.12.1"
pollster = "0.3.0"
raw-window-handle = "0.6.2"
rogue-macros = { path = "./macros" }
winit = "0.30.5"
wgpu = { version = "0.20.1", features = ["webgpu", "vulkan-portability"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.7"
console_log = "1.0"
wasm-bindgen = "0.2.92"
wasm-bindgen-futures = "0.4.42"
web-sys = { version = "0.3.69", features = [
  "Document",
  "Window",
  "Element"
]}
